### ISSUE TITLE
Modify config.toml for GitLab Runner in values.yaml.tpl

### ISSUE THREAD

**Issue by ye** [terraform-google-modules/terraform-google-gke-gitlab#11]
Hi,

I need to enable the [privileged mode](https://docs.gitlab.com/runner/configuration/advanced-configuration.html#the-runnersdocker-section) But I can't seem to get it work with the `values.yaml.tpl`. What's the best way to tweak items in the config.toml?

I've tried to modify the configmaps directly without luck, see below.
![Screen Shot 2019-09-30 at 3 01 24 PM](https://user-images.githubusercontent.com/133924/65907883-31665b00-e393-11e9-9e1d-22a3129da1e9.png)

The configmaps looks like this:
```bash
$ kubectl get configmaps gitlab-gitlab-runner -o yaml
apiVersion: v1
data:
  check-live: |
    #!/bin/bash
    if /usr/bin/pgrep -f .*register-the-runner; then
      exit 0
    elif /usr/bin/pgrep gitlab.*runner; then
      exit 0
    else
      exit 1
    fi
  config.toml: |
    concurrent = 10
    check_interval = 30
    log_level = "info"
    listen_address = '[::]:9252'
    [runners.kubernetes]
      privileged = true
  configure: |
    set -e
    cp /init-secrets/* /secrets
  entrypoint: |
  ...
```
As you can see, I've added the `[runners.kubernetes]` section, which caused the PANIC.

**Comment by viglesiasce** [comment]
The easiest way would be to add the runners.privileged flag in the values file here:
https://github.com/terraform-google-modules/terraform-google-gke-gitlab/blob/master/values.yaml.tpl#L99

More info on the gitlab runner chart:
https://docs.gitlab.com/runner/install/kubernetes.html

**Comment by ye** [comment]
@viglesiasce gotcha. Thanks! 

Once I added the `privileged=true` in,  do I have to do `helm install -f values.yaml` again to make it effective? If so, would that destroy the current GitLab cluster? Current gitlab is running in production and I want to make minimum impact on that runner config change.
