### ISSUE TITLE
Leverage terraform-google-address module for address

### ISSUE THREAD

**Issue by lilithmooncohen** [terraform-google-modules/terraform-google-gke-gitlab#4]
The terraform-google-address module will enable the ability to set dns for the ingress ip

**Comment by tamarintech** [comment]
I have an example with a public IP and DNS here:

https://gitlab.com/e_snyder/gitlab-setup/blob/master/networking.tf#L23

It doesn't use the mentioned module, but might help for reference.

It is used in the chart's values here:

https://gitlab.com/e_snyder/gitlab-setup/blob/master/kubernetes.tf#L118

**Comment by aaron-lane** [comment]
This should be labelled as an enhancement.
