### ISSUE TITLE
Non-empty buckets cause deletion to fail

### ISSUE THREAD

**Issue by henrybell** [terraform-google-modules/terraform-google-gke-gitlab#49]
Currently a Terraform `delete` operation will fail once builds have been run because of non-empty GCS buckets (observed with the "artifacts" bucket). The `force_destroy` option, if applied to a bucket, will cause the bucket to be deleted along with the objects it contains, which will allow deletion of the resource:

https://www.terraform.io/docs/providers/google/r/storage_bucket.html#force_destroy

If this is considered unsafe then this functionality could be exposed with a top-level option (e.g. `force_destroy_buckets` or similar).

**Comment by morgante** [comment]
I think we should add this as a variable.
