### ISSUE TITLE
gitlab_project repo creation failing on subsequent runs

### ISSUE THREAD

**Issue by ameer00** [terraform-google-modules/terraform-google-gke-gitlab#59]
I have a gitlab implementation on GKE.
I am using the Gitlab terraform provider to create a project. Using `gitlab_project` resource.
Here is my `main.tf` file.
```
resource "gitlab_project" "test" {
  name = "test"
  namespace_id = 1
}
```
The first apply completes successfully without issues and the repo is successfully created.
Immediately running `terraform apply` after the first run fails with the following error.
```
Error: PUT https://gitlab.endpoints.projectid.cloud.goog/api/v4/projects/6: 400 {error: allow_merge_on_skipped_pipeline, autoclose_referenced_issues, auto_devops_enabled, auto_devops_deploy_strategy, auto_cancel_pending_pipelines, build_coverage_regex, build_git_strategy, build_timeout, builds_access_level, ci_config_path, ci_default_git_depth, container_registry_enabled, container_expiration_policy_attributes, default_branch, description, emails_disabled, forking_access_level, issues_access_level, lfs_enabled, merge_requests_access_level, merge_method, name, only_allow_merge_if_all_discussions_are_resolved, only_allow_merge_if_pipeline_succeeds, pages_access_level, path, printing_merge_request_link_enabled, public_builds, remove_source_branch_after_merge, repository_access_level, request_access_enabled, resolve_outdated_diff_discussions, shared_runners_enabled, snippets_access_level, tag_list, visibility, wiki_access_level, avatar, suggestion_commit_message, repository_storage, compliance_framework_setting, service_desk_enabled, issues_enabled, jobs_enabled, merge_requests_enabled, wiki_enabled, snippets_enabled are missing, at least one parameter must be provided}

  on main.tf line 1, in resource "gitlab_project" "test":
   1: resource "gitlab_project" "test" {
```
I have produced this error many many times and it is consistent.
I have tried with various terraform versions including `0.12.24`, `0.12.26`, 0.12.29` and `0.13.4`.
They all fail with the same error.

**Comment by morgante** [comment]
It seems like this might be an issue with the GitLab provider itself.

**Comment by ameer00** [comment]
I tested the same file against the public gitlab.com and that works. I did a `terraform apply` multiple times with no issues.
It only seems to fail on the GKE gitlab implementation.

Here is my main.tf file that I used on the public gitlab.

```
provider "gitlab" {
    token = var.token
    base_url = "https://gitlab.com/api/v4/"
}

resource "gitlab_project" "test" {
  name = "testing-tf"
  namespace_id = var.group_id
}
```

using terraform 0.12.24.

```
terraform version            
Terraform v0.12.24
+ provider.gitlab v3.0.0
```

**Comment by ameer00** [comment]
Also, I just tested the `destroy` workflow and that does seem to work fine on Gitlab on GKE

**Comment by morgante** [comment]
I wonder if this is a difference between the provider API version and the version we have deployed in the Helm chart?

**Comment by ameer00** [comment]
I think thats it. I did not have a version specified in my provider block so it was being set to `3.0.0`.
I changed it to `2.9.11` (latest 2.x one) and now it seems to be working now. 👍🏾 
Thanks @morgante

**Comment by morgante** [comment]
Awesome, glad it's working now!
