### ISSUE TITLE
Support terraform version 0.13.X

### ISSUE THREAD

**Issue by symbiont-ji** [terraform-google-modules/terraform-google-gke-gitlab#66]
Already from `terraform init`:
```
Error: Unsupported Terraform Core version

  on .terraform/modules/gke-gitlab.project_services/modules/project_services/versions.tf line 18, in terraform:
  18:   required_version = "~> 0.12.6"
```

**Comment by bharathkkb** [comment]
Hi @symbiont-ji 
Thanks for the report, https://github.com/terraform-google-modules/terraform-google-gke-gitlab/pull/65 should ensure compatibility.

**Comment by oussamarouabah** [comment]
hey, I have encountered the same issue, how can I fix it, please!

**Comment by morgante** [comment]
@oussamarouabah This should be fixed now. Make sure you're using the [latest release](https://github.com/terraform-google-modules/terraform-google-gke-gitlab/blob/master/CHANGELOG.md#050-2021-03-22).
