### ISSUE TITLE
why such a trivial example? 

### ISSUE THREAD

**Issue by symbiont-ji** [terraform-google-modules/terraform-google-gke-gitlab#67]
The example shows nothing. A better example would how how to specify overrides to the default helm chart.

**Comment by bharathkkb** [comment]
Hi @symbiont-ji 
Thanks for the feedback, we generally tend to have 1 simple example that shows how to invoke the module with defaults and we also use for it for [testing](https://github.com/terraform-google-modules/terraform-google-gke-gitlab/tree/master/test) the module. Happy to review any PRs for additional examples that showcase advanced usecases.

**Comment by symbiont-ji** [comment]
What is the point of providing a module if you also do not say how to use
it? As for testing, a trivial example that does not exercise every
component of the module does not count as testing!

/ji

**Comment by symbiont-ji** [comment]
I guess you do not care about the quality of your documentation, right?
