### ISSUE TITLE
With Terraform 0.13.6, "Unsupported Terraform Core version" occurred

### ISSUE THREAD

**Issue by 68user** [terraform-google-modules/terraform-google-gke-gitlab#74]
I want to use gke-gitlab with Terraform 0.13.x.

I try below code:
```
module "gke-gitlab" {
  source                     = "terraform-google-modules/gke-gitlab/google"
  project_id                 = "xxx"
  certmanager_email          = "test@example.com"
}
```
I have got a error.
```
Error: Unsupported Terraform Core version

  on .terraform/modules/gke-gitlab.gke/versions.tf line 18, in terraform:
  18:   required_version = "~> 0.12.6"
```

I think gke-gitlab 0.4.1 supports terraform 0.13.x.
https://github.com/terraform-google-modules/terraform-google-gke-gitlab/blob/release-v0.4.1/CHANGELOG.md

However, in terraform registry, I cannot found gke-gitlab 0.4.1.
There is 0.4.0 as newest version.
https://registry.terraform.io/modules/terraform-google-modules/gke-gitlab/google/latest

Is gke-gitlab 0.4.1 released officially?

**Comment by morgante** [comment]
You can use 0.5.0.
