### ISSUE TITLE
terraform destroy -> terraform apply blocked by SQL instance already exists

### ISSUE THREAD

**Issue by kbroughton** [terraform-google-modules/terraform-google-gke-gitlab#81]
Error, failed to create instance gitlab-db: googleapi: Error 409: The Cloud SQL instance already exists. When you delete an instance, you can't reuse the name of the deleted instance until one week from the deletion date., instanceAlreadyExists

I thought I would be able to get around this issue by setting
gitlab_db_random_prefix = true
but this did not help.

The initial deployment failed because us-central1 did not have enough compute resource to complete the GKE reauest. I changed the region to us-west1 and got the above errror.

To reproduce, 
cd to examples/simple-example
terraform apply
terraform destroy
terraform apply

**Comment by bharathkkb** [comment]
`gitlab_db_random_prefix`  should have set a random prefix. Can you show your plan with this?
