### ISSUE TITLE
Is this module still maintained ?

### ISSUE THREAD

**Issue by paolomainardi** [terraform-google-modules/terraform-google-gke-gitlab#87]
### TL;DR

Hi everyone!

Just wondering if this module is still being actively maintained as the latest release has been released on "May 05, 2021" and some of the new features like the terraform state (https://docs.gitlab.com/ee/user/infrastructure/iac/terraform_state.html) is not taken into consideration.

Should we plan to use it for new projects or not ?

**Comment by apeabody** [comment]
Hi @paolomainardi - Thanks for reaching out.  

We are currently in the process of making some minor updates to this module (e.g. #88, #92 ), and [contributions](https://github.com/terraform-google-modules/terraform-google-gke-gitlab/blob/master/CONTRIBUTING.md) are always welcomed!  If you are looking for a particular new feature, I'd also suggest opening a specific [feature request](https://github.com/terraform-google-modules/terraform-google-gke-gitlab/issues/new?assignees=&labels=enhancement&template=feature.yaml) to enable discussion.

**Comment by paolomainardi** [comment]
Thanks @apeabody nice to know! We have a list stuff that should be fixed/added to make this module work out of the box with the latest Gitlab CE (terraform state bucket, pgsql > 12 etc..), we are going to open specific issues for the needed stuff cc @Syphon83

**Comment by apeabody** [comment]
[Version 2 ](https://github.com/terraform-google-modules/terraform-google-gke-gitlab/releases/tag/v2.0.0) just released.
